'use strict';

const REPRESENTATIONS = [
  'RAW_VALUE',
  'COARSENED_VALUE',
  'DERIVED_PROPERTY',
  'RELATION_ONLY',
  'OPAQUE_TOKEN',
  'REDACTED'
];

const STRATEGIES = [
  'FIXED_REDACTION',
  'STABLE_TOKENIZATION',
  'ORACLE_MIN_DISCLOSURE',
  'RAW_DISCLOSURE'
];

const TASK_IDS = [
  'MD-EQ-01',
  'MD-GROUP-02',
  'MD-ORDER-03',
  'MD-LOC-04',
  'MD-CROSS-05',
  'MD-GRAPH-06',
  'MD-TOOL-07'
];

module.exports = {REPRESENTATIONS, STRATEGIES, TASK_IDS};
